#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  7 19:04:02 2025

@author: james-ashley
"""
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
import os


#Need breakpoints because otherwise there is nothing to prevent the scenario where information is
#lost in the solution as a result of bits of Iapp being jumped over. E.g., the case where Iapp takes
#the same value in two places, but in between it undergoes change; if dt is big enough, it could jump
#over the region of change and the solver wouldn't know.





#Constant current (produces no breakpoints because Iapp=2 exhibits no curvature)

'''Tfinal = 3600
def Iapp(a1):
    return 2 + a1*0

def dIapp(a1):
    return a1*0

def d2Iapp(a1):
    return a1*0
#'''





#Step-function Iapp(t)

'''Iapp0=2
tch1=3600
topen1=60
tdisch1=3570
topen2=60
tchar2=3600
Kiapp=5
Diapp=0


Tfinal = tch1+topen1+tdisch1+topen2+tchar2
def Iapp(a1):
    return (Iapp0*(0.5 + 0.5*np.tanh(Kiapp*((a1) + Diapp))) - Iapp0*(0.5 + 0.5*np.tanh(Kiapp*((a1) - tch1)))-Iapp0*(0.5 + 0.5*np.tanh(Kiapp*((a1) - (tch1+topen1))))+Iapp0*(0.5 + 0.5*np.tanh(Kiapp*((a1) - (tch1+topen1+tdisch1)))) + Iapp0*(0.5 + 0.5*np.tanh(Kiapp*((a1) - (tch1+topen1+tdisch1+topen2)))))

def dIapp(a1):
    return (Iapp0*0.5*(np.cosh(Kiapp*((a1) + Diapp)))**(-2)*Kiapp - Iapp0*0.5*(np.cosh(Kiapp*((a1) - tch1)))**(-2)*Kiapp - Iapp0*0.5*(np.cosh(Kiapp*((a1) - (tch1+topen1))))**(-2)*Kiapp + Iapp0*0.5*(np.cosh(Kiapp*((a1) - (tch1+topen1+tdisch1))))**(-2)*Kiapp + Iapp0*0.5*(np.cosh(Kiapp*((a1) - (tch1+topen1+tdisch1+topen2))))**(-2)*Kiapp)

def d2Iapp(a1):
    return (-Iapp0*(Kiapp**2)*np.tanh(Kiapp*((a1) + Diapp))*(np.cosh(Kiapp*((a1) + Diapp)))**(-2) + Iapp0*(Kiapp**2)*np.tanh(Kiapp*((a1) - tch1))*(np.cosh(Kiapp*((a1) - tch1)))**(-2) + Iapp0*(Kiapp**2)*np.tanh(Kiapp*((a1) - (tch1+topen1)))*(np.cosh(Kiapp*((a1) - (tch1+topen1))))**(-2) -Iapp0*(Kiapp**2)*np.tanh(Kiapp*((a1) - (tch1+topen1+tdisch1)))*(np.cosh(Kiapp*((a1) - (tch1+topen1+tdisch1))))**(-2) - Iapp0*(Kiapp**2)*np.tanh(Kiapp*((a1) - (tch1+topen1+tdisch1+topen2)))*(np.cosh(Kiapp*((a1) - (tch1+topen1+tdisch1+topen2))))**(-2) )
#'''






#Messy Iapp(t)

Tfinal=300
def Iapp(a1):
    return 2 + 0.6*np.sin(2*np.pi*a1/300) + 0.3*np.sin(2*np.pi*a1/75 + 1) + 0.1*np.sin(2*np.pi*a1/20 + 2)

def dIapp(a1):
    return (0.6*(2*np.pi/300)*np.cos(2*np.pi*a1/300) + 0.3*(2*np.pi/75)*np.cos(2*np.pi*a1/75 + 1) + 0.1*(2*np.pi/20)*np.cos(2*np.pi*a1/20 + 2))

def d2Iapp(a1):
    return (-0.6*(2*np.pi/300)**2*np.sin(2*np.pi*a1/300)-0.3*(2*np.pi/75)**2*np.sin(2*np.pi*a1/75 + 1)-0.1*(2*np.pi/20)**2*np.sin(2*np.pi*a1/20 + 2))
#'''





#Curvature
def k(a1):
    return abs(d2Iapp(a1))/((1+(dIapp(a1))**2)**1.5)


dtmaxglobal=5 #Must be selected such that it isn't big enough to jump any sharp gaps. Don't want it too small or else the breakpoints will take longer to compute.
dtmax=dtmaxglobal
dtmin=5e-4 #Must be selected to reflect the smallest timescale of Iapp(t)
cor=1e-6;

t=0
dt=dtmin

breakpoints=[0]

tol=0.1#0.5
while t < Tfinal:

    dt=dt+dtmin
   
    if (dt>dtmax):
        dt=dt-dtmin
        
    er=abs((dIapp(t) - ((Iapp(t) - Iapp(t + dt))/(t-(t + dt))))/(dIapp(t) + cor))
    if (er>tol): 
        while(er>tol):
            dt=dt*0.5#-dtmin
            er=abs((dIapp(t) - ((Iapp(t) - Iapp(t + dt))/(t-(t + dt))))/(dIapp(t) + cor))
            if (dt<dtmin):
                dt=dtmin
                break
        
    t=t+dt
    breakpoints.append(t)
    #print(t)
    if t>Tfinal:
        break

  
breakpoints = np.array(breakpoints)



t = breakpoints       
f = k(breakpoints )
peaks, _ = find_peaks(f)


idx = np.concatenate([peaks])
#idx = np.concatenate([peaks - 1, peaks, peaks + 1])
idx = idx[(idx >= 0) & (idx < len(breakpoints ))]
idx_unique = np.unique(idx)
t_final = breakpoints [idx_unique]
t_final=np.insert(t_final,0,0)





t_dense = np.linspace(0, Tfinal, 150000)
plt.figure(figsize=(8,4))
plt.plot(t_dense, Iapp(t_dense), 'k', lw=1.5, label="$I_{app}(t)$") #50800
plt.scatter(t_final, Iapp(t_final), color='red', s=20, label='Breakpoints')

plt.ylabel("$I_{app}(t)$",fontsize="19")
plt.legend(fontsize="15")
plt.title("Breakpoint Computation",fontsize=15)
plt.tight_layout()
plt.xlabel("$Time$ (s)",fontsize="15")
plt.tick_params(axis='both', labelsize=14)
plt.savefig("Breakpoints2.png", dpi=800, bbox_inches="tight")

plt.show()#'''
  
 
    
# Save to text file (NOTE: ensure this saves to the correct directory before running the FreeFem code; ideally, make sure the FreeFem code and this Python file are in the same directory)

np.savetxt("BreakpointsForFreeFemCode.txt", t_final, fmt="%.10f")
print("Saving breakpoints file to:", os.getcwd())


N = len(t_final)

# Save length on first line, values on second line
with open("BreakpointsForFreeFemCode.txt", "w") as f:
    f.write(f"{N}\n")
    np.savetxt(f, t_final[None, :], fmt="%.10f")




